### ISSUE TITLE
wrong aspect ratio in dsvideo

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#129]
Hello Alex,

As I mentioned yesterday, my girlfriend has noticed from time to time that the aspect ratio is not quite right in dsvideo. She then says she watches the episode via dsfile because everything fits (she's not stupid 😉). 
I have attached two pictures as an example. 

Maybe you can take a look at them. 
Thank you 😊

(https://gist.github.com/Fabian1601/6defd96b9386b66bd74566f633fd94de)

![IMG_2954](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/62207758/d9a5d845-dde8-476c-ad17-1201bc15d349)
![IMG_2953](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/62207758/d86065c1-e406-4b1f-98d3-ee915e98bd3b)

**Comment by AlexPresso** [comment]
Hi @Fabian1601 

Thank you for the report, if you try to play this video without the patch (if it's possible), do you have the same issue ?

**Comment by Fabian1601** [comment]
Hello Alex,
I have installed vdsm and tried it without a patch. 
the video then has the correct ratio in dsvideo 
![IMG_0001](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/62207758/80de47d4-e1c6-4997-bc11-cbcdcc2c54e5)

**Comment by AlexPresso** [comment]
Hi @Fabian1601 

Hope you're doing well, I just deployed a fix tentative (I'm not sure about it but I tried to tune something which I think could be the issue). You can try it using the following commands:

Unpatch your current installation:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
And patch using the fixed wrapper:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a patch -b fix_aspect_ratio`

**Comment by AlexPresso** [comment]
Hi @Fabian1601 
any news on this issue ? did you have time to check the fix ? :)

**Comment by Fabian1601** [comment]
Hello @AlexPresso,
i installed the fix at the weekend and i get the feeling that the problem lies elsewhere....
first i tried the patch in vdsm and everything looked fine.
then i tried it on the normal system but the error remains?!
after that i tried the normal patch in vdsm and the correct aspect ratio remains...
very strange....
so i would say it is not directly related to the patch and would close the issue
